# Calcul matriciel et pièges en numpy

Un des principaux défauts de ```numpy``` (par rapport à des environnement comme Matlab par exemple) est la **différentiation entre les vecteurs et les matrices**... Cet aspect va poser de nombreux problèmes.

Le second défaut réside dans le **dispatch dynamique**: python essaie de faire marcher les calculs, même quand les dimensions des matrices sont incompatibles... Ca fait gagner un peu de temps parfois... Et ça crée des bugs insurmontables d'autres fois.


**Rappel:**

Pour executer une cellule : Shift + Entrée

**Exercices** (marqués <span style="color:red"> EXO</span>) Des exercices sont proposés régulièrement dans le notebook pour éviter *l'effet contemplatif* des exemples. Si vous maitrisez déjà les concepts de base et que les solutions vous semblent évidentes, n'héstiez pas à sauter des questions.

Tous les exercices sont classés par ordre d'importance:  <span style="color:red"> 1</span>="essentiel", <span style="color:red">2</span>="utile, <span style="color:red">3</span>="optionnel et/ou avancé"

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Produit matriciel

Il ne faut pas confondre le produit terme à terme, entre matrices de mêmes dimensions et le produit matriciel qui est un ensemble de produits scalaires. 
Dans le produit matriciel, le nombre de colonne de la première matrice doit correspondre au nombre de ligne de la seconde/


<img src="./ressources/matrix_mult.png" width="200px">

$$ {\color {red}c_{{12}}}=\sum _{{r=1}}^{2}a_{{1r}}b_{{r2}}=a_{{11}}b_{{12}}+a_{{12}}b_{{22}}$$

$$ {\color {blue}c_{{33}}}=\sum _{{r=1}}^{2}a_{{3r}}b_{{r3}}=a_{{31}}b_{{13}}+a_{{32}}b_{{23}}$$

In [2]:
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B = np.array([[5., 4, 3], [2, 1, 0]])
print("A=",A,"\n B=",B)

# calcul de produit matriciel, par différents moyens
C  = A@B # le plus clair (d'après moi)
C2 = A.dot(B)

print(C)

A= [[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]] 
 B= [[5. 4. 3.]
 [2. 1. 0.]]
[[ 2.  1.  0.]
 [16. 11.  6.]
 [30. 21. 12.]
 [44. 31. 18.]]


In [3]:
# test sur des matrices incompatibles (matriciel)
# le nombre de colonne de A doit être égal au nombre de ligne de B

A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
M = np.array([[0., 1], [2, 3], [4, 5]])

print(A@M) # matriciel

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [4]:
# et le produit terme à terme, uniquement entre matrices de même dimension

print(A*M) # terme à terme

ValueError: operands could not be broadcast together with shapes (4,2) (3,2) 

In [5]:
# et le produit terme à terme, uniquement entre matrices de même dimension
# cas correct

A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
A2 = np.array([[1., 2], [2, 1], [1, 2], [2, 1]])

print(A*A2)

[[ 0.  2.]
 [ 4.  3.]
 [ 4. 10.]
 [12.  7.]]


In [6]:
# test sur des données incompatibles (terme à terme)

C3 = A*B # Comprendre le message d'erreur (il va être récurrent !)

ValueError: operands could not be broadcast together with shapes (4,2) (2,3) 

### <span style="color:red"> EXO (3) reprogrammer la multiplication matricielle </span>

[plutot pour les étudiants qui ne sont pas familier avec le produit matriciel]
1. Dessiner les matrice au brouillon
2. Algo en 3 boucles à identifier

In [9]:
# soit les matrices (compatibles)
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B = np.array([[5., 4, 3], [2, 1, 0]])

# fonction de calcul matricielle

def calc_mat(a, b):
    """calcul le produit matriciel de a par b"""
    C = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]): # parcours des lignes de a
        for j in range(b.shape[1]): # parcours des colonnes de b
            for k in range(a.shape[1]): # parcours des colonnes de a (ou lignes de b)
                C[i,j] += a[i,k]*b[k,j]
    return C

# test
print("REFERENCE")
print(A@B)
print("NOUVELLE FONCTION")
print(calc_mat(A,B))

REFERENCE
[[ 2.  1.  0.]
 [16. 11.  6.]
 [30. 21. 12.]
 [44. 31. 18.]]
NOUVELLE FONCTION
[[ 2.  1.  0.]
 [16. 11.  6.]
 [30. 21. 12.]
 [44. 31. 18.]]


## Types de données

In [10]:
# Les commandes ci-dessous créent des vecteurs

v1=np.random.rand(10)
v2=np.array([1, 4, 18])
v3=np.ones(12)

print(v1.shape)

(10,)


In [11]:
# Les commandes ci-dessous créent des matrices

m1=np.random.rand(10,2)
m2=np.array([[1, 4, 18],[2, 4, 6]])
m3=np.ones((12,2))

print(m1.shape)

(10, 2)


In [12]:
# Cas limite
# attention, ces deux objets ne vont pas avoir le même comportement selon les fonctions utilisées

v2 = np.array([1, 4, 18])
# et 
m2 = np.array([[1, 4, 18]])

print("v2 et m2 ne sont pas du même type: ", v2.shape, m2.shape)

tv2 = np.ones((3, 3))@v2
print(tv2) # il prend le vecteur en colonne => OK
tv2_bis = v2@np.ones((3, 3))
print(tv2_bis) # il prend le vecteur en ligne => OK
tm2 = np.ones((3, 3))@m2
print(tm2) # les dimensions sont incompatibles (pas de degré de liberté quand les dimensions sont fixées)


v2 et m2 ne sont pas du même type:  (3,) (1, 3)
[23. 23. 23.]
[23. 23. 23.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [ ]:
# extraire une ligne ou une colonne => générer un vecteur (et pas une matrice)
# => nous sommes obligé de jongler avec les types de données

m1 = np.random.rand(10,3)
v4 = m1[:,1]   # extraction d'une colonne => vecteur
m4 = m1[:,1:3] # extraction de deux colonnes => matrice
x1 = m1[:,1:2] # extraction d'une seule colonnes, mais en syntaxe matricielle => ???

print(v4.shape, m4.shape)
print(x1.shape) # => matrice !!

### Pourquoi ces différences de types posent problème?

In [13]:
# Definition de 3 versions de B

A     = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B_col = np.array([[1.], [2]]) # matrice (=en forme de vecteur colonne)
B_li  = np.array([[1., 2]])   # matrice (=en forme de vecteur ligne)
B_vec = np.array([1., 2])     # vecteur


In [14]:

# les cas qui marchent
print(A@B_col)
print(A@B_vec) # les résultats n'ont pas les mêmes dimensions
print(A.dot(B_col))
print(A.dot(B_vec)) # les résultats n'ont pas les mêmes dimensions

print("\n")

# 
print(A*B_li)    # Catastrophe => ca ne fait pas d'erreur
print(A*B_vec)   # Catastrophe => ca ne fait pas d'erreur

[[ 2.]
 [ 8.]
 [14.]
 [20.]]
[ 2.  8. 14. 20.]
[[ 2.]
 [ 8.]
 [14.]
 [20.]]
[ 2.  8. 14. 20.]


[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]
[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [ ]:
# les cas qui ne marchent pas (1)
print(A@B_li) # KO pour les dimensions => raisonnable, mais attention aux versions de python


In [ ]:
# les cas qui ne marchent pas (2)

print(A*B_col) # Erreur => c'est logique

In [ ]:
B_col = np.array([[1.], [2]]) # matrice (=en forme de vecteur colonne)
B_li  = np.array([[1., 2]])   # matrice (=en forme de vecteur ligne)
B_vec = np.array([1., 2])     #

print(B_li@B_col) # le calcul est propre... Et renvoie une matrice
# print(B_li@B_li)  # KO
print(B_vec@B_vec) # produit scalaire
print(B_vec@B_col) # renvoie un vecteur


In [ ]:
# tentons dans l'autre sens
# 
print(B_col @ B_li) # renvoie une matrice (OK)
# print(B_col @ B_vec) # KO : alors qu'on  voudrait intuitivement que ça marche
print(B_vec * B_li) # OK
print(B_vec * B_col) # => WAOUH , carrement n'importe quoi !!

## Dispatch dynamique

Beaucoup de comportements étranges sont liés à cette fonctionnalité. Partons d'un exemple simple et étudions les différentes solutions pratiques:

    # Soit la matrice A:
    A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
    # Je souhaite multiplier chaque ligne par le vecteur [1,2]

In [ ]:
# Soit la matrice A:
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])

# Je souhaite multiplier chaque ligne par le vecteur [1,2]


In [ ]:
# solution 1: developpeur standard avec des boucles

B = A.copy()
for ligne in B:
    ligne *= [1,2]
print(B)

In [ ]:
# solution 2: raisonnement matriciel, je veux juste multiplier la seconde colonne par un scalaire
B = A.copy()
B[:,1] *= 2
print(B)

In [ ]:
# solution 3: je crée une matrice pour ensuite faire une multiplication terme à terme

M = np.ones((4,2))
M[:,1] *= 2
B = A*M
print(B)

In [ ]:
# solution 4: dispatch dynamique
# ça ne devrait pas marcher... MAIS
#   1. python détecte que le nb de colonne est compatible
#   2. python applique l'opération sur chaque ligne automatiquement
#   => pratique... Mais risqué: il faut connaitre ce truc pour détecter les bugs associés

B = A * [1,2]
print(B)

In [ ]:
# pour faire la même chose sur les colonnes
# à multiplier par [1, 2, 3, 4]

B = A * [[1],[2],[3],[4]] # il faut présenter un vecteur colonne pour que python accepte le dispatch
print(B)

## <span style="color:red"> EXO produit divers</span>

Soit une matrice de dimension $(n,d)$ remplie de 1. Chercher la formule qui permet de passer à une matrice $[1,2,...,d]$ répété respectivement sur les lignes ou les colonnes:

$ M = \begin{pmatrix}
1 & 1 & \ldots &1 \\
1 & 1 & \ldots & 1 \\
\vdots &  \vdots & \ddots & \vdots \\
1 & 1 & \ldots & 1 \\
\end{pmatrix} 
\Rightarrow 
\begin{pmatrix}
1 & 2 & \ldots &d \\
1 & 2 & \ldots & d \\
\vdots &  \vdots & \ddots & \vdots \\
1 & 2 & \ldots & d \\
\end{pmatrix} \text{ ou }
\begin{pmatrix}
1 & 1 & \ldots &1 \\
2 & 2 & \ldots & 2 \\
\vdots &  \vdots & \ddots & \vdots \\
n & n & \ldots & n \\
\end{pmatrix}$

In [ ]:
mat = np.ones((5,5))

def transformation_colonnes(mat):
    for i in range(mat.shape[1]):
        mat[:,i] *= (i+1)
    return mat

def transformation_lignes(mat):
    for j in range(mat.shape[0]):
        mat[j,:] *= (j+1)
    return mat

print(transformation_lignes(mat))
print( transformation_colonnes(mat))



[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]


## <span style="color:red"> EXO Evaluation d'une fonction linéaire</span>

Soit une matrice $X$ de dimension $(n,d)$ stockant $n$ échantillon $\mathbf x_i \in \mathbb R^d$ et un vecteur de paramètres $w \in \mathbb R^d$, 

$ X = \begin{pmatrix}
x_{11} & x_{12} & \ldots & x_{1d} \\
x_{21} & x_{22} & \ldots & x_{2d} \\
\vdots &  \vdots & \ddots & \vdots \\
x_{n1} & x_{n2} & \ldots & x_{nd} \\
\end{pmatrix} 
\qquad
W = \begin{pmatrix}
w_{1} & w_{2} & \ldots & w_{d} 
\end{pmatrix} 
$

Calculer l'ensemble : $\forall i, f(\mathbf x_i) = \sum_{j=1}^d x_{ij} w_j $
Cet ensemble sera stocké dans un vecteur.

In [42]:
n = 100
d = 10
X = np.random.rand(n,d)
W = np.arange(d)

In [51]:
W = W.reshape((-1,1)) 
yi = X@W
print(yi)

[[21.72008545]
 [22.81272126]
 [28.80131464]
 [31.04696583]
 [19.10069781]
 [25.92303324]
 [22.34479209]
 [28.66424983]
 [20.1915694 ]
 [27.23318135]
 [ 9.52011198]
 [31.92976066]
 [24.52870459]
 [26.05265863]
 [17.46167455]
 [17.42746616]
 [24.18162903]
 [30.74622631]
 [24.63217799]
 [22.35430462]
 [15.45453734]
 [28.3766998 ]
 [12.98538713]
 [35.03656331]
 [24.26795256]
 [25.92642475]
 [19.945072  ]
 [17.5457106 ]
 [16.17312417]
 [27.41020432]
 [34.96895453]
 [19.76441265]
 [21.65517587]
 [28.61592454]
 [18.26614603]
 [22.8871053 ]
 [27.63705862]
 [27.759173  ]
 [16.20023847]
 [26.94291955]
 [14.37231376]
 [26.03396336]
 [29.88782784]
 [23.10404207]
 [22.56351646]
 [16.56745741]
 [18.27494913]
 [28.76753047]
 [23.27437698]
 [14.81652592]
 [15.77386308]
 [17.49960345]
 [25.57202398]
 [20.43717164]
 [17.74526759]
 [20.23310408]
 [21.03084751]
 [12.94559825]
 [22.29692347]
 [18.60461266]
 [21.07926741]
 [24.86648214]
 [22.92504118]
 [13.23105407]
 [26.95387319]
 [25.5135209 ]
 [19.40616

# Construction du sujet à partir de la correction

In [ ]:
###  TODO )"," TODO ",\
    txt, flags=re.DOTALL))
f2.close()

### </CORRECTION> ###